# Generated by Django 5.0.4 on 2024-05-03 09:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ocr_app', '0002_aadhaarcard_pancard_delete_extractedtext'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExtractedText',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField()),
            ],
        ),
        migrations.DeleteModel(
            name='AadhaarCard',
        ),
        migrations.DeleteModel(
            name='PANCard',
        ),
    ]
