# Generated by Django 5.0.4 on 2024-11-26 07:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ocr_app', '0004_aadhaarcard_pancard_delete_extractedtext'),
    ]

    operations = [
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('document_type', models.CharField(choices=[('AADHAR', 'Aadhar Card'), ('PAN', 'Pan Card')], max_length=50)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('image_path', models.ImageField(upload_to='uploaded_documents/')),
            ],
        ),
        migrations.CreateModel(
            name='Visitor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('birth_date', models.DateField()),
                ('age', models.PositiveIntegerField()),
                ('email', models.EmailField(max_length=254)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='VisitorPass',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('qr_code_data', models.TextField()),
                ('expiry_date', models.DateField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('visitor', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='visitor_pass', to='ocr_app.visitor')),
            ],
        ),
        migrations.DeleteModel(
            name='AadhaarCard',
        ),
        migrations.DeleteModel(
            name='PANCard',
        ),
        migrations.AddField(
            model_name='document',
            name='visitor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='ocr_app.visitor'),
        ),
    ]
